dist: xenial
language: node_js
node_js:
   - "8"
before_install:
  - echo "Nothing"
  - sudo apt-get install libfontconfig1 fontconfig libfontconfig1-dev libfreetype6-dev
  - export PHANTOM_JS="phantomjs-2.1.1-linux-x86_64"
  - wget https://github.com/Medium/phantomjs/releases/download/v2.1.1/$PHANTOM_JS.tar.bz2
  - sudo tar xvjf $PHANTOM_JS.tar.bz2
  - sudo mv $PHANTOM_JS /usr/local/share
  - sudo ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin
  - phantomjs --version
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bundle install
  - bower install
  - grunt prod
notifications:
  email: true
# Taken from:  https://github.com/mdix/es6-babel-browserify-karma-boilerplate/blob/master/.travis.yml#L3

#trying test
